### ISSUE TITLE
libSoC

### ISSUE THREAD

**Issue by koenkooi** [96boards/96BoardsGPIO#1]
Have you looked at https://github.com/jackmitch/libsoc ?

**Comment by dmandala** [comment]
Had not seen that lib, it looks interesting, will look into it.  Looks like that could further along on SPI and I2c.

**Comment by dmandala** [comment]
I'll see if I can have a conversation with the gent, while the lib is very general it does not help as much with the 96Board specific items.  But if he is interested might be able to work together.  His lib is more mature but would need extensive adaption to 96Boards, the lib appears to be SoC specific and this lib is more board specific since it would be possible for 2 96Boards to use the same SoC but use very different pins exported to the board.

**Comment by dmandala** [comment]
Have sent the gent an email to see if he is interested in patches to support 96Boards.  It's a very nice library but does not solve the difference between boards that 96BoardGPIO does now.  The experimental branch has a blink.c program that once compiled will run on the dragon, hikey and bubblegum without a recompile or touching the code in any way.  That is what I'd like him to accept is patches that allow that behavior.

Hopefully I'll hear back soonish.

**Comment by dmandala** [comment]
We now have patches in libsoc making it use 96Boards GPIO naming and we are in process of adding Python support.
